# Automatically generated by configure - do not modify
SRC_PATH=/home/mickours/POLYTHEC_RICM4/Qemu/qemu_stm32L/rendu/Sources/Qemu/src/roms/vgabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
